"""AI price briefing component.

Renders an on-demand AI price analysis card inside route expanders.
The briefing is generated by DeepSeekBriefingAnalyzer (with automatic
fallback to rule-based analysis) and cached in st.session_state for
12 hours (or until manually refreshed).
"""

from datetime import date, datetime, timezone
from statistics import median
from typing import Dict, Any, List, Tuple

import streamlit as st

from flightscanner.interfaces import FlightPrice
from flightscanner.core.services import RouteWithLatestPrice
from flightscanner.analyzers.deepseek_analyzer import generate_brief_with_fallback
from flightscanner.analyzers.rule_based_analyzer import _batch_min_prices
from flightscanner.utils.config import settings


# ── Helpers ───────────────────────────────────────────────────────────────────

_TREND_ICONS: Dict[str, str] = {
    "上涨": "📈",
    "下跌": "📉",
    "震荡": "〰️",
    "稳定": "➡️",
}

_ALERT_STYLES: Dict[str, str] = {
    "low":    "background:#ecfdf5;border-left:4px solid #10b981;padding:0.6rem 0.9rem;border-radius:0 8px 8px 0;",
    "medium": "background:#fffbeb;border-left:4px solid #f59e0b;padding:0.6rem 0.9rem;border-radius:0 8px 8px 0;",
    "high":   "background:#fef2f2;border-left:4px solid #ef4444;padding:0.6rem 0.9rem;border-radius:0 8px 8px 0;",
}

_ALERT_LABELS: Dict[str, str] = {
    "low":    "低风险",
    "medium": "中等风险",
    "high":   "高风险 / 建议尽快行动",
}


def _12h_window_id() -> int:
    """Return an integer that increments every 12 hours (UTC)."""
    return int(datetime.now(timezone.utc).timestamp() // (12 * 3600))


def _should_auto_trigger(price_history: List[FlightPrice]) -> Tuple[bool, str]:
    """Return (should_trigger, reason_label).

    Conditions (any one suffices):
    1. ≥ 5 distinct scrape batches — data milestone.
    2. Current batch min deviates ≥ 8 % from historical median — price anomaly.
    The 12 h interval is implicit: cache key _12h_window_id() expires every 12 h.
    """
    if not price_history:
        return False, ""

    batch_mins = _batch_min_prices(price_history)
    batch_count = len(batch_mins)

    # Condition 2: price anomaly (checked first for better label)
    sorted_recs = sorted(price_history, key=lambda fp: fp.scraped_at, reverse=True)
    latest_bid = sorted_recs[0].batch_id
    if latest_bid:
        cur_batch = [fp for fp in price_history if fp.batch_id == latest_bid]
        cur_min = min(float(fp.price) for fp in cur_batch)
        hist_recs = [fp for fp in price_history if fp.batch_id != latest_bid]
    else:
        cur_min = float(sorted_recs[0].price)
        hist_recs = price_history[1:]

    hist_mins = _batch_min_prices(hist_recs)
    if len(hist_mins) >= 2:
        hist_med = median(hist_mins)
        if hist_med > 0:
            dev = abs(cur_min - hist_med) / hist_med
            if dev >= 0.08:
                arrow = "↓" if cur_min < hist_med else "↑"
                return True, f"价格异动 {arrow}{dev * 100:.0f}%"

    # Condition 1: data milestone
    if batch_count >= 5:
        return True, f"已累积 {batch_count} 批数据"

    return False, ""


def _render_brief_card(brief: Dict[str, Any]) -> None:
    """Render a formatted AI briefing result card.

    Args:
        brief: Dict conforming to the AI output JSON schema.
    """
    trend = brief.get("trend", "稳定")
    confidence = brief.get("confidence", 0.0)
    key_factors = brief.get("key_factors", [])
    prediction_7d = brief.get("prediction_7d", "")
    recommendation = brief.get("recommendation", "")
    alert_level = brief.get("alert_level", "medium")
    source = brief.get("_source", "")

    icon = _TREND_ICONS.get(trend, "➡️")
    style = _ALERT_STYLES.get(alert_level, _ALERT_STYLES["medium"])
    alert_label = _ALERT_LABELS.get(alert_level, "")
    conf_pct = int(confidence * 100)

    # ── Alert-level banner ───────────────────────────────────────────────────
    st.markdown(
        f'<div style="{style}">'
        f'<strong>{icon} 趋势：{trend}</strong>　|　'
        f'置信度 {conf_pct}%　|　{alert_label}'
        f"</div>",
        unsafe_allow_html=True,
    )

    # ── Key factors ──────────────────────────────────────────────────────────
    if key_factors:
        factors_html = "".join(
            f'<span style="display:inline-block;background:#f1f5f9;'
            f'border-radius:6px;padding:2px 8px;margin:2px;font-size:0.80rem;">'
            f"{f}</span>"
            for f in key_factors
        )
        st.markdown(
            f'<div style="margin:0.5rem 0 0.25rem;">'
            f'<span style="font-size:0.75rem;color:#64748b;font-weight:600;">'
            f"关键因素</span><br>{factors_html}</div>",
            unsafe_allow_html=True,
        )

    # ── 7-day prediction ─────────────────────────────────────────────────────
    if prediction_7d:
        st.caption(f"**7日预测**：{prediction_7d}")

    # ── Recommendation ───────────────────────────────────────────────────────
    if recommendation:
        st.markdown(
            f'<div style="margin-top:0.5rem;padding:0.5rem 0.8rem;'
            f'background:#f8fafc;border-radius:8px;'
            f'font-size:0.875rem;font-weight:600;color:#0f172a;">'
            f"💡 建议：{recommendation}</div>",
            unsafe_allow_html=True,
        )

    # ── Source badge ─────────────────────────────────────────────────────────
    label = "DeepSeek AI" if source == "deepseek" else "规则引擎（AI 降级）"
    st.caption(f"分析来源：{label}　·　{date.today()}")


# ── Main render function ──────────────────────────────────────────────────────

def render_ai_brief(
    route: RouteWithLatestPrice,
    price_history: List[FlightPrice],
) -> None:
    """Render the AI briefing section inside an expanded route card.

    Auto-triggers generation when:
    - ≥ 5 distinct scrape batches accumulated (data milestone), or
    - Current batch min deviates ≥ 8% from historical median (price anomaly).
    Otherwise shows a manual generation button.
    The result is cached per 12-hour window in st.session_state.

    Args:
        route:         Route data including target date.
        price_history: Historical price records (30-day window).
    """
    cache_key = f"ai_brief_{route.id}_{_12h_window_id()}"
    st.markdown('<p class="fs-section-subtitle">AI 价格简报</p>', unsafe_allow_html=True)

    if cache_key not in st.session_state:
        should_trigger, reason = _should_auto_trigger(price_history)
        if should_trigger:
            with st.spinner(f"AI 分析中（{reason}）…"):
                brief = generate_brief_with_fallback(
                    price_history=price_history,
                    target_date=route.target_date,
                    route_label=f"{route.origin} → {route.destination}",
                    api_key=settings.deepseek_api_key or None,
                    base_url=settings.deepseek_base_url,
                    model=settings.deepseek_model,
                )
            st.session_state[cache_key] = brief
            # fall through to render
        else:
            if st.button(
                "✨ 生成 AI 简报",
                key=f"ai_btn_{route.id}",
                help="调用 DeepSeek AI 分析价格趋势并给出购票建议（12小时缓存）",
            ):
                with st.spinner("正在生成 AI 价格分析…"):
                    brief = generate_brief_with_fallback(
                        price_history=price_history,
                        target_date=route.target_date,
                        route_label=f"{route.origin} → {route.destination}",
                        api_key=settings.deepseek_api_key or None,
                        base_url=settings.deepseek_base_url,
                        model=settings.deepseek_model,
                    )
                st.session_state[cache_key] = brief
                st.rerun()
            return

    _render_brief_card(st.session_state[cache_key])

    if st.button(
        "🔄 重新生成",
        key=f"ai_refresh_{route.id}",
        help="清除缓存并重新生成 AI 简报",
    ):
        del st.session_state[cache_key]
        st.rerun()
