"""AI price briefing component.

Renders an on-demand AI price analysis card inside route expanders.
The briefing is generated by DeepSeekBriefingAnalyzer (with automatic
fallback to rule-based analysis) and cached on disk keyed off a data
fingerprint — regenerated only when new scrape data arrives, never on
page re-render or app restart.
"""

import json
from datetime import date
from pathlib import Path
from statistics import median
from typing import Dict, Any, List, Optional, Tuple

import streamlit as st

from flightscanner.interfaces import FlightPrice
from flightscanner.core.services import RouteWithLatestPrice
from flightscanner.analyzers.deepseek_analyzer import generate_brief_with_fallback
from flightscanner.analyzers.rule_based_analyzer import _batch_min_prices
from flightscanner.utils.config import settings


# ── Cross-restart disk persistence ────────────────────────────────────────────
# st.session_state and @st.cache_data (in-memory) are lost on Streamlit server
# restart. Persist briefs here so app startup never triggers an AI call when
# the underlying price data hasn't changed.

_BRIEF_CACHE_DIR = Path(".cache/ai_briefs")


def _brief_cache_file(route_id: int) -> Path:
    return _BRIEF_CACHE_DIR / f"route_{route_id}.json"


def _load_brief_from_disk(route_id: int) -> Optional[Dict[str, Any]]:
    """Return {"fingerprint": str, "brief": dict} or None if missing/corrupt."""
    path = _brief_cache_file(route_id)
    if not path.exists():
        return None
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(payload, dict) and "fingerprint" in payload and "brief" in payload:
            return payload
    except Exception:
        pass
    return None


def _save_brief_to_disk(route_id: int, fingerprint: str, brief: Dict[str, Any]) -> None:
    try:
        _BRIEF_CACHE_DIR.mkdir(parents=True, exist_ok=True)
        _brief_cache_file(route_id).write_text(
            json.dumps(
                {"fingerprint": fingerprint, "brief": brief},
                ensure_ascii=False,
                default=str,
            ),
            encoding="utf-8",
        )
    except Exception:
        pass  # persistence is best-effort; never break rendering


def _clear_brief_from_disk(route_id: int) -> None:
    try:
        _brief_cache_file(route_id).unlink(missing_ok=True)
    except Exception:
        pass


@st.cache_data(ttl=12 * 3600, show_spinner=False)
def _cached_generate_brief(
    route_id: int,
    fingerprint: str,
    target_date: date,
    route_label: str,
    api_key: Optional[str],
    base_url: str,
    model: str,
    evolution_context: str,
    _price_history: List,
) -> Dict[str, Any]:
    """Disk-cached wrapper around generate_brief_with_fallback.

    Cache key is (route_id, fingerprint, ...). `fingerprint` changes only
    when new price data arrives, so identical data always hits the cache
    instead of calling the AI on every render. The leading underscore on
    _price_history excludes it from Streamlit's hash computation so we
    avoid serializing complex FlightPrice objects.
    """
    return generate_brief_with_fallback(
        price_history=_price_history,
        target_date=target_date,
        route_label=route_label,
        api_key=api_key,
        base_url=base_url,
        model=model,
        evolution_context=evolution_context,
    )


# ── Helpers ───────────────────────────────────────────────────────────────────

_TREND_ICONS: Dict[str, str] = {
    "上涨": "📈",
    "下跌": "📉",
    "震荡": "〰️",
    "稳定": "➡️",
}

_ALERT_STYLES: Dict[str, str] = {
    "low":    "background:#ecfdf5;border-left:4px solid #10b981;padding:0.6rem 0.9rem;border-radius:0 8px 8px 0;",
    "medium": "background:#fffbeb;border-left:4px solid #f59e0b;padding:0.6rem 0.9rem;border-radius:0 8px 8px 0;",
    "high":   "background:#fef2f2;border-left:4px solid #ef4444;padding:0.6rem 0.9rem;border-radius:0 8px 8px 0;",
}

_ALERT_LABELS: Dict[str, str] = {
    "low":    "低风险",
    "medium": "中等风险",
    "high":   "高风险 / 建议尽快行动",
}


def _data_fingerprint(price_history: List[FlightPrice]) -> str:
    """Return a fingerprint that changes only when new price data arrives.

    Used as the cache key so the AI brief is regenerated only after a new
    scrape batch produces data — not on every frontend render or every 12 h
    wall-clock window.
    """
    if not price_history:
        return "empty"
    latest = max(price_history, key=lambda fp: fp.scraped_at)
    bid = latest.batch_id or ""
    return f"{bid}|{latest.scraped_at.isoformat()}|{len(price_history)}"


def _get_session_local():
    """获取 SessionLocal 工厂（延迟导入避免循环依赖）。"""
    from ui.utils.db import get_session_local  # lazy import
    return get_session_local()


def _get_credibility(route_id: int) -> Dict[str, Any]:
    """获取路线信誉数据（G4 辅助）。

    Args:
        route_id: 路线 ID。

    Returns:
        信誉字典（win_rate, evaluated_count, consecutive_fatal_losses, circuit_broken）。
    """
    try:
        from flightscanner.analyzers.evolution_engine import get_route_credibility  # lazy
        SessionLocal = _get_session_local()
        with SessionLocal() as session:
            return get_route_credibility(session, route_id)
    except Exception:
        return {"win_rate": 0.0, "evaluated_count": 0, "consecutive_fatal_losses": 0, "circuit_broken": False}


def _get_evolution_context(route_id: int) -> str:
    """获取 G4 进化上下文字符串（注入 AI prompt）。

    Args:
        route_id: 路线 ID。

    Returns:
        历史预测摘要字符串，空字符串表示无历史数据。
    """
    try:
        from flightscanner.analyzers.evolution_engine import build_evolved_context  # lazy
        SessionLocal = _get_session_local()
        with SessionLocal() as session:
            return build_evolved_context(session, route_id)
    except Exception:
        return ""


def _should_auto_trigger(price_history: List[FlightPrice]) -> Tuple[bool, str]:
    """Return (should_trigger, reason_label).

    Conditions (any one suffices):
    1. ≥ 5 distinct scrape batches — data milestone.
    2. Current batch min deviates ≥ 8 % from historical median — price anomaly.
    This is only consulted by the caller when new price data has arrived since
    the last brief (i.e. the data fingerprint has changed).
    """
    if not price_history:
        return False, ""

    batch_mins = _batch_min_prices(price_history)
    batch_count = len(batch_mins)

    # Condition 2: price anomaly (checked first for better label)
    sorted_recs = sorted(price_history, key=lambda fp: fp.scraped_at, reverse=True)
    latest_bid = sorted_recs[0].batch_id
    if latest_bid:
        cur_batch = [fp for fp in price_history if fp.batch_id == latest_bid]
        cur_min = min(float(fp.price) for fp in cur_batch)
        hist_recs = [fp for fp in price_history if fp.batch_id != latest_bid]
    else:
        cur_min = float(sorted_recs[0].price)
        hist_recs = price_history[1:]

    hist_mins = _batch_min_prices(hist_recs)
    if len(hist_mins) >= 2:
        hist_med = median(hist_mins)
        if hist_med > 0:
            dev = abs(cur_min - hist_med) / hist_med
            if dev >= 0.08:
                arrow = "↓" if cur_min < hist_med else "↑"
                return True, f"价格异动 {arrow}{dev * 100:.0f}%"

    # Condition 1: data milestone
    if batch_count >= 5:
        return True, f"已累积 {batch_count} 批数据"

    return False, ""


def _render_credibility_badge(route_id: int) -> None:
    """从 DB 读取信誉数据并渲染 badge + circuit breaker 提示。

    仅在有 ≥ MIN_EVALUATED_FOR_CREDIBILITY 条已评估预测时显示。

    Args:
        route_id: 路线 ID。
    """
    from flightscanner.analyzers.evolution_engine import MIN_EVALUATED_FOR_CREDIBILITY  # lazy

    cred = _get_credibility(route_id)
    if cred["evaluated_count"] < MIN_EVALUATED_FOR_CREDIBILITY:
        return

    win_rate = cred["win_rate"]
    if win_rate >= 0.7:
        color = "#10b981"
    elif win_rate >= 0.5:
        color = "#f59e0b"
    else:
        color = "#ef4444"

    label = f"AI胜率 {win_rate * 100:.0f}% ({cred['evaluated_count']}次)"
    st.markdown(
        f'<span class="fs-chip" style="color:{color};border-color:{color};">{label}</span>',
        unsafe_allow_html=True,
    )
    if cred["circuit_broken"]:
        st.warning("⚠️ AI 近期连续误判，简报仅供参考")


def _render_brief_card(brief: Dict[str, Any], route_id: Optional[int] = None) -> None:
    """Render a formatted AI briefing result card.

    Args:
        brief: Dict conforming to the AI output JSON schema.
        route_id: Route ID used to render the credibility badge (optional).
    """
    trend = brief.get("trend", "稳定")
    confidence = brief.get("confidence", 0.0)
    key_factors = brief.get("key_factors", [])
    prediction_7d = brief.get("prediction_7d", "")
    recommendation = brief.get("recommendation", "")
    alert_level = brief.get("alert_level", "medium")
    source = brief.get("_source", "")

    icon = _TREND_ICONS.get(trend, "➡️")
    style = _ALERT_STYLES.get(alert_level, _ALERT_STYLES["medium"])
    alert_label = _ALERT_LABELS.get(alert_level, "")
    conf_pct = int(confidence * 100)

    # ── Alert-level banner ───────────────────────────────────────────────────
    st.markdown(
        f'<div style="{style}">'
        f'<strong>{icon} 趋势：{trend}</strong>　|　'
        f'置信度 {conf_pct}%　|　{alert_label}'
        f"</div>",
        unsafe_allow_html=True,
    )

    # ── Key factors ──────────────────────────────────────────────────────────
    if key_factors:
        factors_html = "".join(
            f'<span style="display:inline-block;background:#f1f5f9;'
            f'border-radius:6px;padding:2px 8px;margin:2px;font-size:0.80rem;">'
            f"{f}</span>"
            for f in key_factors
        )
        st.markdown(
            f'<div style="margin:0.5rem 0 0.25rem;">'
            f'<span style="font-size:0.75rem;color:#64748b;font-weight:600;">'
            f"关键因素</span><br>{factors_html}</div>",
            unsafe_allow_html=True,
        )

    # ── 7-day prediction ─────────────────────────────────────────────────────
    if prediction_7d:
        st.caption(f"**7日预测**：{prediction_7d}")

    # ── Recommendation ───────────────────────────────────────────────────────
    if recommendation:
        st.markdown(
            f'<div style="margin-top:0.5rem;padding:0.5rem 0.8rem;'
            f'background:#f8fafc;border-radius:8px;'
            f'font-size:0.875rem;font-weight:600;color:#0f172a;">'
            f"💡 建议：{recommendation}</div>",
            unsafe_allow_html=True,
        )

    # ── Source badge ─────────────────────────────────────────────────────────
    label = "DeepSeek AI" if source == "deepseek" else "规则引擎（AI 降级）"
    st.caption(f"分析来源：{label}　·　{date.today()}")

    # ── Credibility badge (G4) ────────────────────────────────────────────────
    if route_id is not None:
        _render_credibility_badge(route_id)


# ── Main render function ──────────────────────────────────────────────────────

def render_ai_brief(
    route: RouteWithLatestPrice,
    price_history: List[FlightPrice],
) -> None:
    """Render the AI briefing section inside an expanded route card.

    Regeneration strategy: the brief is persisted to disk per-route and keyed
    off a **data fingerprint** (latest batch_id + scraped_at + record count).
    On app startup / new session the brief is hydrated from disk — no AI call,
    no trigger check, no spinner. Re-renders with unchanged data always reuse
    the cached brief. Trigger conditions are only evaluated when new data has
    actually arrived since the last brief.

    Auto-triggers generation (on new data) when:
    - ≥ 5 distinct scrape batches accumulated (data milestone), or
    - Current batch min deviates ≥ 8% from historical median (price anomaly).
    Otherwise the previous brief is kept (if any), or a manual button shown.

    Args:
        route:         Route data including target date.
        price_history: Historical price records (30-day window).
    """
    cache_key = f"ai_brief_{route.id}"
    fp_key = f"ai_brief_fp_{route.id}"
    current_fp = _data_fingerprint(price_history)

    # ── Hydrate session_state from disk on first access in this session ───────
    if cache_key not in st.session_state:
        disk = _load_brief_from_disk(route.id)
        if disk is not None:
            st.session_state[cache_key] = disk["brief"]
            st.session_state[fp_key] = disk["fingerprint"]

    last_fp = st.session_state.get(fp_key)

    st.markdown('<p class="fs-section-subtitle">AI 价格简报</p>', unsafe_allow_html=True)

    # ── Circuit breaker guard (G4) ────────────────────────────────────────────
    cred = _get_credibility(route.id)
    if cred.get("circuit_broken"):
        st.warning("⚠️ AI 近期连续误判，已暂停自动分析。如需继续请手动触发。")
        if not st.button("强制生成", key=f"ai_force_{route.id}"):
            return

    # ── Fast path: unchanged data + cached brief → reuse without any checks ──
    if cache_key in st.session_state and last_fp == current_fp:
        _render_brief_card(st.session_state[cache_key], route_id=route.id)
        if st.button(
            "🔄 重新生成",
            key=f"ai_refresh_{route.id}",
            help="清除缓存并重新生成 AI 简报",
        ):
            st.session_state.pop(cache_key, None)
            st.session_state.pop(fp_key, None)
            _cached_generate_brief.clear()
            _clear_brief_from_disk(route.id)
            st.rerun()
        return

    # ── Data changed (or first render): evaluate trigger conditions ──────────
    should_trigger, reason = _should_auto_trigger(price_history)

    if should_trigger:
        evolution_ctx = _get_evolution_context(route.id)
        with st.spinner(f"AI 分析中（{reason}）…"):
            brief = _cached_generate_brief(
                route_id=route.id,
                fingerprint=current_fp,
                target_date=route.target_date,
                route_label=f"{route.origin} → {route.destination}",
                api_key=settings.deepseek_api_key or None,
                base_url=settings.deepseek_base_url,
                model=settings.deepseek_model,
                evolution_context=evolution_ctx,
                _price_history=price_history,
            )
        st.session_state[cache_key] = brief
        st.session_state[fp_key] = current_fp
        _save_brief_to_disk(route.id, current_fp, brief)
        # fall through to render
    elif cache_key in st.session_state:
        # New data but trigger conditions not met — keep the old brief and
        # bump the fingerprint so we don't re-check on every render. Persist
        # the updated fingerprint so next restart also skips the trigger check.
        st.session_state[fp_key] = current_fp
        _save_brief_to_disk(route.id, current_fp, st.session_state[cache_key])
        # fall through to render
    else:
        # No cached brief and trigger conditions not met — offer manual button.
        if st.button(
            "✨ 生成 AI 简报",
            key=f"ai_btn_{route.id}",
            help="调用 DeepSeek AI 分析价格趋势并给出购票建议",
        ):
            evolution_ctx = _get_evolution_context(route.id)
            with st.spinner("正在生成 AI 价格分析…"):
                brief = _cached_generate_brief(
                    route_id=route.id,
                    fingerprint=current_fp,
                    target_date=route.target_date,
                    route_label=f"{route.origin} → {route.destination}",
                    api_key=settings.deepseek_api_key or None,
                    base_url=settings.deepseek_base_url,
                    model=settings.deepseek_model,
                    evolution_context=evolution_ctx,
                    _price_history=price_history,
                )
            st.session_state[cache_key] = brief
            st.session_state[fp_key] = current_fp
            _save_brief_to_disk(route.id, current_fp, brief)
            st.rerun()
        return

    _render_brief_card(st.session_state[cache_key], route_id=route.id)

    if st.button(
        "🔄 重新生成",
        key=f"ai_refresh_{route.id}",
        help="清除缓存并重新生成 AI 简报",
    ):
        st.session_state.pop(cache_key, None)
        st.session_state.pop(fp_key, None)
        _cached_generate_brief.clear()
        _clear_brief_from_disk(route.id)
        st.rerun()
